name: "mnist"
platform: "onnxruntime_onnx"
max_batch_size: 1
input [
  {
    name: "x" # 모델의 실제 입력 이름으로 수정 
    data_type: TYPE_FP32
    dims: [ 1, 28, 28 ]
  }
]
output [
  {
    name: "dense_2" # 모델의 실제 출력 이름으로 수정
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]
